/*
 * hi6555v2_driver codec driver.
 *
 * Copyright (c) 2015 Hisilicon Technologies CO., Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef __HI6555V2_ASP_REG_DEF_H__
#define __HI6555V2_ASP_REG_DEF_H__

#define ASP_CODEC_BASE 0x2000
#define ASP_CFG_BASE 0xE000

#define CODEC_REG_BIT0  0
#define CODEC_REG_BIT1  1
#define CODEC_REG_BIT2  2
#define CODEC_REG_BIT3  3
#define CODEC_REG_BIT4  4
#define CODEC_REG_BIT5  5
#define CODEC_REG_BIT6  6
#define CODEC_REG_BIT7  7
#define CODEC_REG_BIT8  8
#define CODEC_REG_BIT9  9
#define CODEC_REG_BIT10 10
#define CODEC_REG_BIT11 11
#define CODEC_REG_BIT12 12
#define CODEC_REG_BIT13 13
#define CODEC_REG_BIT14 14
#define CODEC_REG_BIT15 15
#define CODEC_REG_BIT16 16
#define CODEC_REG_BIT17 17
#define CODEC_REG_BIT18 18
#define CODEC_REG_BIT19 19
#define CODEC_REG_BIT20 20
#define CODEC_REG_BIT21 21
#define CODEC_REG_BIT22 22
#define CODEC_REG_BIT23 23
#define CODEC_REG_BIT24 24
#define CODEC_REG_BIT25 25
#define CODEC_REG_BIT26 26
#define CODEC_REG_BIT27 27
#define CODEC_REG_BIT28 28
#define CODEC_REG_BIT29 29
#define CODEC_REG_BIT30 30
#define CODEC_REG_BIT31 31

#define VERSION_REG                        (ASP_CODEC_BASE + 0x0)             /* CODEC版本寄存器 */
#define VERSION_LEN    32
#define VERSION_OFFSET 0

#define CODEC_CLK_EN0_REG                  (ASP_CODEC_BASE + 0x4)             /* CODEC子模块时钟门控寄存器0 */
#define SDM_R_CLKEN_LEN    1
#define SDM_R_CLKEN_OFFSET 31
#define SDM_L_CLKEN_LEN    1
#define SDM_L_CLKEN_OFFSET 30
#define DACR_UP16_CLKEN_LEN    1
#define DACR_UP16_CLKEN_OFFSET 29
#define DACL_UP16_CLKEN_LEN    1
#define DACL_UP16_CLKEN_OFFSET 28
#define DACR_FILTER_CLKEN_LEN    1
#define DACR_FILTER_CLKEN_OFFSET 27
#define DACL_FILTER_CLKEN_LEN    1
#define DACL_FILTER_CLKEN_OFFSET 26
#define DACR_SRCUP_CLKEN_LEN    1
#define DACR_SRCUP_CLKEN_OFFSET 25
#define DACL_SRCUP_CLKEN_LEN    1
#define DACL_SRCUP_CLKEN_OFFSET 24
#define DACR_MIXER4_CLKEN_LEN    1
#define DACR_MIXER4_CLKEN_OFFSET 23
#define DACL_MIXER4_CLKEN_LEN    1
#define DACL_MIXER4_CLKEN_OFFSET 22
#define VOICE_L_DN_SRCUP_CLKEN_LEN    1
#define VOICE_L_DN_SRCUP_CLKEN_OFFSET 21
#define AUDIO_R_DN_PGA_CLKEN_LEN    1
#define AUDIO_R_DN_PGA_CLKEN_OFFSET 20
#define AUDIO_L_DN_PGA_CLKEN_LEN    1
#define AUDIO_L_DN_PGA_CLKEN_OFFSET 19
#define VOICE_L_DN_PGA_CLKEN_LEN    1
#define VOICE_L_DN_PGA_CLKEN_OFFSET 18
#define BT_TX_MIXER2_CLKEN_LEN    1
#define BT_TX_MIXER2_CLKEN_OFFSET 17
#define BT_TX_SRCDN_CLKEN_LEN    1
#define BT_TX_SRCDN_CLKEN_OFFSET 16
#define BT_R_RX_SRCDN_CLKEN_LEN    1
#define BT_R_RX_SRCDN_CLKEN_OFFSET 15
#define BT_L_RX_SRCDN_CLKEN_LEN    1
#define BT_L_RX_SRCDN_CLKEN_OFFSET 14
#define BT_R_RX_SRCUP_CLKEN_LEN    1
#define BT_R_RX_SRCUP_CLKEN_OFFSET 13
#define BT_L_RX_SRCUP_CLKEN_LEN    1
#define BT_L_RX_SRCUP_CLKEN_OFFSET 12
#define BT_R_RX_PGA_CLKEN_LEN    1
#define BT_R_RX_PGA_CLKEN_OFFSET 11
#define BT_L_RX_PGA_CLKEN_LEN    1
#define BT_L_RX_PGA_CLKEN_OFFSET 10
#define MIC3_UP_AFIFO_CLKEN_LEN    1
#define MIC3_UP_AFIFO_CLKEN_OFFSET 9
#define VOICE_R_UP_AFIFO_CLKEN_LEN    1
#define VOICE_R_UP_AFIFO_CLKEN_OFFSET 8
#define VOICE_L_UP_AFIFO_CLKEN_LEN    1
#define VOICE_L_UP_AFIFO_CLKEN_OFFSET 7
#define AUDIO_R_UP_AFIFO_CLKEN_LEN    1
#define AUDIO_R_UP_AFIFO_CLKEN_OFFSET 6
#define AUDIO_L_UP_AFIFO_CLKEN_LEN    1
#define AUDIO_L_UP_AFIFO_CLKEN_OFFSET 5
#define AUDIO_R_DN_AFIFO_CLKEN_LEN    1
#define AUDIO_R_DN_AFIFO_CLKEN_OFFSET 4
#define AUDIO_L_DN_AFIFO_CLKEN_LEN    1
#define AUDIO_L_DN_AFIFO_CLKEN_OFFSET 3
#define VOICE_L_DN_AFIFO_CLKEN_LEN    1
#define VOICE_L_DN_AFIFO_CLKEN_OFFSET 2
#define SPA_R_UP_AFIFO_CLKEN_LEN    1
#define SPA_R_UP_AFIFO_CLKEN_OFFSET 1
#define SPA_L_UP_AFIFO_CLKEN_LEN    1
#define SPA_L_UP_AFIFO_CLKEN_OFFSET 0

#define CODEC_CLK_EN1_REG                  (ASP_CODEC_BASE + 0x8)             /* CODEC子模块时钟门控寄存器1 */
#define I2S2_PCM_CLKEN_LEN    1
#define I2S2_PCM_CLKEN_OFFSET 31
#define I2S1_TDM_CLKEN_LEN    1
#define I2S1_TDM_CLKEN_OFFSET 30
#define MIC3_UP_PGA_CLKEN_LEN    1
#define MIC3_UP_PGA_CLKEN_OFFSET 29
#define MIC3_UP_SRCDN_CLKEN_LEN    1
#define MIC3_UP_SRCDN_CLKEN_OFFSET 28
#define VOICE_R_UP_SRCDN_CLKEN_LEN    1
#define VOICE_R_UP_SRCDN_CLKEN_OFFSET 27
#define VOICE_L_UP_SRCDN_CLKEN_LEN    1
#define VOICE_L_UP_SRCDN_CLKEN_OFFSET 26
#define AUDIO_R_UP_SRCUP_CLKEN_LEN    1
#define AUDIO_R_UP_SRCUP_CLKEN_OFFSET 25
#define AUDIO_L_UP_SRCUP_CLKEN_LEN    1
#define AUDIO_L_UP_SRCUP_CLKEN_OFFSET 24
#define AUDIO_R_UP_PGA_CLKEN_LEN    1
#define AUDIO_R_UP_PGA_CLKEN_OFFSET 23
#define AUDIO_L_UP_PGA_CLKEN_LEN    1
#define AUDIO_L_UP_PGA_CLKEN_OFFSET 22
#define SIDETONE_PGA_CLKEN_LEN    1
#define SIDETONE_PGA_CLKEN_OFFSET 21
#define ADC_MIC3_FILTER_CLKEN_LEN    1
#define ADC_MIC3_FILTER_CLKEN_OFFSET 20
#define ADCR_FILTER_CLKEN_LEN    1
#define ADCR_FILTER_CLKEN_OFFSET 19
#define ADCL_FILTER_CLKEN_LEN    1
#define ADCL_FILTER_CLKEN_OFFSET 18
#define SIF_MST_CLKEN_LEN    1
#define SIF_MST_CLKEN_OFFSET 17
#define ECHO_R_UP_SRCDN_CLKEN_LEN    1
#define ECHO_R_UP_SRCDN_CLKEN_OFFSET 16
#define ECHO_L_UP_SRCDN_CLKEN_LEN    1
#define ECHO_L_UP_SRCDN_CLKEN_OFFSET 15
#define ECHO_R_UP_AFIFO_CLKEN_LEN    1
#define ECHO_R_UP_AFIFO_CLKEN_OFFSET 14
#define ECHO_L_UP_AFIFO_CLKEN_LEN    1
#define ECHO_L_UP_AFIFO_CLKEN_OFFSET 13
#define I2S3_PCM_CLKEN_LEN    1
#define I2S3_PCM_CLKEN_OFFSET 9
#define VOICE_R_DN_SRCUP_CLKEN_LEN    1
#define VOICE_R_DN_SRCUP_CLKEN_OFFSET 8
#define VOICE_R_DN_PGA_CLKEN_LEN    1
#define VOICE_R_DN_PGA_CLKEN_OFFSET 7
#define CODEC3_R_DN_AFIFO_CLKEN_LEN    1
#define CODEC3_R_DN_AFIFO_CLKEN_OFFSET 6
#define CODEC3_L_DN_AFIFO_CLKEN_LEN    1
#define CODEC3_L_DN_AFIFO_CLKEN_OFFSET 5
#define VOICE_R_DN_AFIFO_CLKEN_LEN    1
#define VOICE_R_DN_AFIFO_CLKEN_OFFSET 4
#define RST_3MIC_VOICE_IRQ_LEN    1
#define RST_3MIC_VOICE_IRQ_OFFSET 2
#define RST_3MIC_AUDIO_IRQ_LEN    1
#define RST_3MIC_AUDIO_IRQ_OFFSET 1
#define SLV_MODE_441_LEN    1
#define SLV_MODE_441_OFFSET 0

#define CODEC_SW_RST_N_REG                 (ASP_CODEC_BASE + 0xC)             /* CODEC子系统全局复位 */
#define SW_RST_N_LEN    1
#define SW_RST_N_OFFSET 0

#define I2S1_TDM_CTRL0_REG                 (ASP_CODEC_BASE + 0x10)            /* I2S1_TDM接口控制寄存器0 */
#define I2S1_RX_CLK_SEL_LEN    1
#define I2S1_RX_CLK_SEL_OFFSET 31
#define I2S1_TX_CLK_SEL_LEN    1
#define I2S1_TX_CLK_SEL_OFFSET 30
#define I2S1_CODEC_IO_WORDLENGTH_LEN    2
#define I2S1_CODEC_IO_WORDLENGTH_OFFSET 28
#define I2S1_CODEC_DATA_FORMAT_LEN    1
#define I2S1_CODEC_DATA_FORMAT_OFFSET 27
#define I2S1_CHNNL_MODE_LEN    1
#define I2S1_CHNNL_MODE_OFFSET 26
#define I2S1_LRCLK_MODE_LEN    1
#define I2S1_LRCLK_MODE_OFFSET 25
#define I2S1_FRAME_MODE_LEN    1
#define I2S1_FRAME_MODE_OFFSET 24
#define I2S1_FUNC_MODE_LEN    3
#define I2S1_FUNC_MODE_OFFSET 21
#define I2S1_DIRECT_LOOP_LEN    2
#define I2S1_DIRECT_LOOP_OFFSET 19
#define I2S1_MST_SLV_LEN    1
#define I2S1_MST_SLV_OFFSET 18
#define I2S1_IF_RX_ENA_LEN    1
#define I2S1_IF_RX_ENA_OFFSET 17
#define I2S1_IF_TX_ENA_LEN    1
#define I2S1_IF_TX_ENA_OFFSET 16
#define TDM1_RX_SLOT_SEL_V0_LEN    4
#define TDM1_RX_SLOT_SEL_V0_OFFSET 12
#define TDM1_RX_SLOT_SEL_I0_LEN    4
#define TDM1_RX_SLOT_SEL_I0_OFFSET 8
#define TDM1_RX_SLOT_SEL_V1_LEN    4
#define TDM1_RX_SLOT_SEL_V1_OFFSET 4
#define TDM1_RX_SLOT_SEL_I1_LEN    4
#define TDM1_RX_SLOT_SEL_I1_OFFSET 0

#define I2S1_TDM_CTRL1_REG                 (ASP_CODEC_BASE + 0x14)            /* I2S1_TDM接口控制寄存器1 */
#define TDM1_TX_CHAN_SEL_R_LEN    3
#define TDM1_TX_CHAN_SEL_R_OFFSET 29
#define TDM1_TX_CHAN_SEL_L_LEN    3
#define TDM1_TX_CHAN_SEL_L_OFFSET 26
#define TDM1_DIRECT_LOOP_LEN    2
#define TDM1_DIRECT_LOOP_OFFSET 24
#define TDM1_FRAME_MODE_LEN    1
#define TDM1_FRAME_MODE_OFFSET 23
#define TDM1_RX_CLK_SEL_LEN    1
#define TDM1_RX_CLK_SEL_OFFSET 22
#define TDM1_TX_CLK_SEL_LEN    1
#define TDM1_TX_CLK_SEL_OFFSET 21
#define TDM1_IF_RX_ENA_LEN    1
#define TDM1_IF_RX_ENA_OFFSET 20
#define TDM1_IF_TX_ENA_LEN    1
#define TDM1_IF_TX_ENA_OFFSET 19
#define I2S1_TDM_MODE_LEN    1
#define I2S1_TDM_MODE_OFFSET 18
#define I2S2_RX_CLK_SEL_LEN    1

#define I2S2_PCM_CTRL_REG                  (ASP_CODEC_BASE + 0x18)            /* I2S1_PCM接口控制寄存器 */
#define I2S2_RX_CLK_SEL_OFFSET 31
#define I2S2_TX_CLK_SEL_LEN    1
#define I2S2_TX_CLK_SEL_OFFSET 30
#define I2S2_CODEC_IO_WORDLENGTH_LEN    2
#define I2S2_CODEC_IO_WORDLENGTH_OFFSET 28
#define I2S2_CODEC_DATA_FORMAT_LEN    1
#define I2S2_CODEC_DATA_FORMAT_OFFSET 27
#define I2S2_CHNNL_MODE_LEN    1
#define I2S2_CHNNL_MODE_OFFSET 26
#define I2S2_LRCLK_MODE_LEN    1
#define I2S2_LRCLK_MODE_OFFSET 25
#define I2S2_FRAME_MODE_LEN    1
#define I2S2_FRAME_MODE_OFFSET 24
#define I2S2_FUNC_MODE_LEN    3
#define I2S2_FUNC_MODE_OFFSET 21
#define I2S2_DIRECT_LOOP_LEN    2
#define I2S2_DIRECT_LOOP_OFFSET 19
#define I2S2_MST_SLV_LEN    1
#define I2S2_MST_SLV_OFFSET 18
#define I2S2_IF_RX_ENA_LEN    1
#define I2S2_IF_RX_ENA_OFFSET 17
#define I2S2_IF_TX_ENA_LEN    1
#define I2S2_IF_TX_ENA_OFFSET 16
#define FS_I2S2_LEN    3
#define FS_I2S2_OFFSET 13

#define PGA_THRE_CTRL0_REG                 (ASP_CODEC_BASE + 0x1C)            /* PGA/MIXER阈值控制寄存器0 */
#define PGA_MIXER_THRE_CTRL0_LEN    32
#define PGA_MIXER_THRE_CTRL0_OFFSET 0

#define PGA_THRE_CTRL1_REG                 (ASP_CODEC_BASE + 0x20)            /* PGA/MIXER阈值控制寄存器1 */
#define PGA_MIXER_THRE_CTRL1_LEN    32
#define PGA_MIXER_THRE_CTRL1_OFFSET 0

#define PGA_THRE_CTRL2_REG                 (ASP_CODEC_BASE + 0x24)            /* PGA/MIXER阈值控制寄存器2 */
#define PGA_MIXER_THRE_CTRL2_LEN    32
#define PGA_MIXER_THRE_CTRL2_OFFSET 0

#define PGA_GAINOFFSET_CTRL0_REG           (ASP_CODEC_BASE + 0x28)            /* PGA GAINOFFSET配置寄存器0 */
#define VOICE_L_DN_PGA_GAINOFFSET_LEN    8
#define VOICE_L_DN_PGA_GAINOFFSET_OFFSET 24
#define AUDIO_L_DN_PGA_GAINOFFSET_LEN    8
#define AUDIO_L_DN_PGA_GAINOFFSET_OFFSET 16
#define AUDIO_R_DN_PGA_GAINOFFSET_LEN    8
#define AUDIO_R_DN_PGA_GAINOFFSET_OFFSET 8
#define SIDETONE_PGA_GAINOFFSET_LEN    8
#define SIDETONE_PGA_GAINOFFSET_OFFSET 0

#define PGA_GAINOFFSET_CTRL1_REG           (ASP_CODEC_BASE + 0x2C)            /* PGA GAINOFFSET配置寄存器1 */
#define AUDIO_L_UP_PGA_GAINOFFSET_LEN    8
#define AUDIO_L_UP_PGA_GAINOFFSET_OFFSET 24
#define AUDIO_R_UP_PGA_GAINOFFSET_LEN    8
#define AUDIO_R_UP_PGA_GAINOFFSET_OFFSET 16
#define BT_L_RX_PGA_GAINOFFSET_LEN    8
#define BT_L_RX_PGA_GAINOFFSET_OFFSET 8
#define BT_R_RX_PGA_GAINOFFSET_LEN    8
#define BT_R_RX_PGA_GAINOFFSET_OFFSET 0

#define PGA_GAINOFFSET_CTRL2_REG           (ASP_CODEC_BASE + 0x30)            /* PGA GAINOFFSET配置寄存器2 */
#define MIC3_UP_PGA_GAINOFFSET_LEN    8
#define MIC3_UP_PGA_GAINOFFSET_OFFSET 24
#define VOICE_R_DN_PGA_GAINOFFSET_LEN    8
#define VOICE_R_DN_PGA_GAINOFFSET_OFFSET 16

#define VOICE_L_DN_PGA_CTRL_REG            (ASP_CODEC_BASE + 0x34)            /* VOICE下行PGA控制寄存器 */
#define VOICE_L_DN_PGA_GAIN_LEN    8
#define VOICE_L_DN_PGA_GAIN_OFFSET 24
#define VOICE_L_DN_PGA_CFG_LEN    3
#define VOICE_L_DN_PGA_CFG_OFFSET 21
#define VOICE_L_DN_PGA_FADE_IN_LEN    5
#define VOICE_L_DN_PGA_FADE_IN_OFFSET 16
#define VOICE_L_DN_PGA_FADE_OUT_LEN    5
#define VOICE_L_DN_PGA_FADE_OUT_OFFSET 11
#define VOICE_L_DN_PGA_BYPASS_LEN    1
#define VOICE_L_DN_PGA_BYPASS_OFFSET 10
#define VOICE_L_DN_PGA_NOISE_EN_LEN    1
#define VOICE_L_DN_PGA_NOISE_EN_OFFSET 9
#define VOICE_L_DN_PGA_THRE_ID_LEN    2
#define VOICE_L_DN_PGA_THRE_ID_OFFSET 7
#define VOICE_L_DN_PGA_ZERO_NUM_LEN    5
#define VOICE_L_DN_PGA_ZERO_NUM_OFFSET 2
#define VOICE_L_DN_PGA_LINEAR_SEL_LEN    1
#define VOICE_L_DN_PGA_LINEAR_SEL_OFFSET 1

#define AUDIO_L_DN_PGA_CTRL_REG            (ASP_CODEC_BASE + 0x38)            /* AUDIO下行通路左声道PGA控制寄存器 */
#define AUDIO_L_DN_PGA_GAIN_LEN    8
#define AUDIO_L_DN_PGA_GAIN_OFFSET 24
#define AUDIO_L_DN_PGA_CFG_LEN    3
#define AUDIO_L_DN_PGA_CFG_OFFSET 21
#define AUDIO_L_DN_PGA_FADE_IN_LEN    5
#define AUDIO_L_DN_PGA_FADE_IN_OFFSET 16
#define AUDIO_L_DN_PGA_FADE_OUT_LEN    5
#define AUDIO_L_DN_PGA_FADE_OUT_OFFSET 11
#define AUDIO_L_DN_PGA_BYPASS_LEN    1
#define AUDIO_L_DN_PGA_BYPASS_OFFSET 10
#define AUDIO_L_DN_PGA_NOISE_EN_LEN    1
#define AUDIO_L_DN_PGA_NOISE_EN_OFFSET 9
#define AUDIO_L_DN_PGA_THRE_ID_LEN    2
#define AUDIO_L_DN_PGA_THRE_ID_OFFSET 7
#define AUDIO_L_DN_PGA_ZERO_NUM_LEN    5
#define AUDIO_L_DN_PGA_ZERO_NUM_OFFSET 2
#define AUDIO_L_DN_PGA_LINEAR_SEL_LEN    1
#define AUDIO_L_DN_PGA_LINEAR_SEL_OFFSET 1

#define AUDIO_R_DN_PGA_CTRL_REG            (ASP_CODEC_BASE + 0x3C)            /* AUDIO下行通路右声道PGA控制寄存器 */
#define AUDIO_R_DN_PGA_GAIN_LEN    8
#define AUDIO_R_DN_PGA_GAIN_OFFSET 24
#define AUDIO_R_DN_PGA_CFG_LEN    3
#define AUDIO_R_DN_PGA_CFG_OFFSET 21
#define AUDIO_R_DN_PGA_FADE_IN_LEN    5
#define AUDIO_R_DN_PGA_FADE_IN_OFFSET 16
#define AUDIO_R_DN_PGA_FADE_OUT_LEN    5
#define AUDIO_R_DN_PGA_FADE_OUT_OFFSET 11
#define AUDIO_R_DN_PGA_BYPASS_LEN    1
#define AUDIO_R_DN_PGA_BYPASS_OFFSET 10
#define AUDIO_R_DN_PGA_NOISE_EN_LEN    1
#define AUDIO_R_DN_PGA_NOISE_EN_OFFSET 9
#define AUDIO_R_DN_PGA_THRE_ID_LEN    2
#define AUDIO_R_DN_PGA_THRE_ID_OFFSET 7
#define AUDIO_R_DN_PGA_ZERO_NUM_LEN    5
#define AUDIO_R_DN_PGA_ZERO_NUM_OFFSET 2
#define AUDIO_R_DN_PGA_LINEAR_SEL_LEN    1
#define AUDIO_R_DN_PGA_LINEAR_SEL_OFFSET 1

#define SIDETONE_PGA_CTRL_REG              (ASP_CODEC_BASE + 0x40)            /* SIDETONE通路PGA控制寄存器 */
#define SIDETONE_PGA_GAIN_LEN    8
#define SIDETONE_PGA_GAIN_OFFSET 24
#define SIDETONE_PGA_CFG_LEN    3
#define SIDETONE_PGA_CFG_OFFSET 21
#define SIDETONE_PGA_FADE_IN_LEN    5
#define SIDETONE_PGA_FADE_IN_OFFSET 16
#define SIDETONE_PGA_FADE_OUT_LEN    5
#define SIDETONE_PGA_FADE_OUT_OFFSET 11
#define SIDETONE_PGA_BYPASS_LEN    1
#define SIDETONE_PGA_BYPASS_OFFSET 10
#define SIDETONE_PGA_NOISE_EN_LEN    1
#define SIDETONE_PGA_NOISE_EN_OFFSET 9
#define SIDETONE_PGA_THRE_ID_LEN    2
#define SIDETONE_PGA_THRE_ID_OFFSET 7
#define SIDETONE_PGA_ZERO_NUM_LEN    5
#define SIDETONE_PGA_ZERO_NUM_OFFSET 2
#define SIDETONE_PGA_LINEAR_SEL_LEN    1
#define SIDETONE_PGA_LINEAR_SEL_OFFSET 1

#define AUDIO_L_UP_PGA_CTRL_REG            (ASP_CODEC_BASE + 0x44)            /* AUDIO上行通路左声道PGA控制寄存器 */
#define AUDIO_L_UP_PGA_GAIN_LEN    8
#define AUDIO_L_UP_PGA_GAIN_OFFSET 24
#define AUDIO_L_UP_PGA_CFG_LEN    3
#define AUDIO_L_UP_PGA_CFG_OFFSET 21
#define AUDIO_L_UP_PGA_FADE_IN_LEN    5
#define AUDIO_L_UP_PGA_FADE_IN_OFFSET 16
#define AUDIO_L_UP_PGA_FADE_OUT_LEN    5
#define AUDIO_L_UP_PGA_FADE_OUT_OFFSET 11
#define AUDIO_L_UP_PGA_BYPASS_LEN    1
#define AUDIO_L_UP_PGA_BYPASS_OFFSET 10
#define AUDIO_L_UP_PGA_NOISE_EN_LEN    1
#define AUDIO_L_UP_PGA_NOISE_EN_OFFSET 9
#define AUDIO_L_UP_PGA_THRE_ID_LEN    2
#define AUDIO_L_UP_PGA_THRE_ID_OFFSET 7
#define AUDIO_L_UP_PGA_ZERO_NUM_LEN    5
#define AUDIO_L_UP_PGA_ZERO_NUM_OFFSET 2
#define AUDIO_L_UP_PGA_LINEAR_SEL_LEN    1
#define AUDIO_L_UP_PGA_LINEAR_SEL_OFFSET 1

#define AUDIO_R_UP_PGA_CTRL_REG            (ASP_CODEC_BASE + 0x48)            /* AUDIO上行通路右声道PGA控制寄存器 */
#define AUDIO_R_UP_PGA_GAIN_LEN    8
#define AUDIO_R_UP_PGA_GAIN_OFFSET 24
#define AUDIO_R_UP_PGA_CFG_LEN    3
#define AUDIO_R_UP_PGA_CFG_OFFSET 21
#define AUDIO_R_UP_PGA_FADE_IN_LEN    5
#define AUDIO_R_UP_PGA_FADE_IN_OFFSET 16
#define AUDIO_R_UP_PGA_FADE_OUT_LEN    5
#define AUDIO_R_UP_PGA_FADE_OUT_OFFSET 11
#define AUDIO_R_UP_PGA_BYPASS_LEN    1
#define AUDIO_R_UP_PGA_BYPASS_OFFSET 10
#define AUDIO_R_UP_PGA_NOISE_EN_LEN    1
#define AUDIO_R_UP_PGA_NOISE_EN_OFFSET 9
#define AUDIO_R_UP_PGA_THRE_ID_LEN    2
#define AUDIO_R_UP_PGA_THRE_ID_OFFSET 7
#define AUDIO_R_UP_PGA_ZERO_NUM_LEN    5
#define AUDIO_R_UP_PGA_ZERO_NUM_OFFSET 2
#define AUDIO_R_UP_PGA_LINEAR_SEL_LEN    1
#define AUDIO_R_UP_PGA_LINEAR_SEL_OFFSET 1

#define BT_L_RX_PGA_CTRL_REG               (ASP_CODEC_BASE + 0x4C)            /* BT通路RX方向左声道PGA控制寄存器 */
#define BT_L_RX_PGA_GAIN_LEN    8
#define BT_L_RX_PGA_GAIN_OFFSET 24
#define BT_L_RX_PGA_CFG_LEN    3
#define BT_L_RX_PGA_CFG_OFFSET 21
#define BT_L_RX_PGA_FADE_IN_LEN    5
#define BT_L_RX_PGA_FADE_IN_OFFSET 16
#define BT_L_RX_PGA_FADE_OUT_LEN    5
#define BT_L_RX_PGA_FADE_OUT_OFFSET 11
#define BT_L_RX_PGA_BYPASS_LEN    1
#define BT_L_RX_PGA_BYPASS_OFFSET 10
#define BT_L_RX_PGA_NOISE_EN_LEN    1
#define BT_L_RX_PGA_NOISE_EN_OFFSET 9
#define BT_L_RX_PGA_THRE_ID_LEN    2
#define BT_L_RX_PGA_THRE_ID_OFFSET 7
#define BT_L_RX_PGA_ZERO_NUM_LEN    5
#define BT_L_RX_PGA_ZERO_NUM_OFFSET 2
#define BT_L_RX_PGA_LINEAR_SEL_LEN    1
#define BT_L_RX_PGA_LINEAR_SEL_OFFSET 1

#define BT_R_RX_PGA_CTRL_REG               (ASP_CODEC_BASE + 0x50)            /* BT通路RX方向右声道PGA控制寄存器 */
#define BT_R_RX_PGA_GAIN_LEN    8
#define BT_R_RX_PGA_GAIN_OFFSET 24
#define BT_R_RX_PGA_CFG_LEN    3
#define BT_R_RX_PGA_CFG_OFFSET 21
#define BT_R_RX_PGA_FADE_IN_LEN    5
#define BT_R_RX_PGA_FADE_IN_OFFSET 16
#define BT_R_RX_PGA_FADE_OUT_LEN    5
#define BT_R_RX_PGA_FADE_OUT_OFFSET 11
#define BT_R_RX_PGA_BYPASS_LEN    1
#define BT_R_RX_PGA_BYPASS_OFFSET 10
#define BT_R_RX_PGA_NOISE_EN_LEN    1
#define BT_R_RX_PGA_NOISE_EN_OFFSET 9
#define BT_R_RX_PGA_THRE_ID_LEN    2
#define BT_R_RX_PGA_THRE_ID_OFFSET 7
#define BT_R_RX_PGA_ZERO_NUM_LEN    5
#define BT_R_RX_PGA_ZERO_NUM_OFFSET 2
#define BT_R_RX_PGA_LINEAR_SEL_LEN    1
#define BT_R_RX_PGA_LINEAR_SEL_OFFSET 1

#define MIC3_UP_PGA_CTRL_REG               (ASP_CODEC_BASE + 0x54)            /* MIC3上行通路PGA控制寄存器 */
#define MIC3_UP_PGA_GAIN_LEN    8
#define MIC3_UP_PGA_GAIN_OFFSET 24
#define MIC3_UP_PGA_CFG_LEN    3
#define MIC3_UP_PGA_CFG_OFFSET 21
#define MIC3_UP_PGA_FADE_IN_LEN    5
#define MIC3_UP_PGA_FADE_IN_OFFSET 16
#define MIC3_UP_PGA_FADE_OUT_LEN    5
#define MIC3_UP_PGA_FADE_OUT_OFFSET 11
#define MIC3_UP_PGA_BYPASS_LEN    1
#define MIC3_UP_PGA_BYPASS_OFFSET 10
#define MIC3_UP_PGA_NOISE_EN_LEN    1
#define MIC3_UP_PGA_NOISE_EN_OFFSET 9
#define MIC3_UP_PGA_THRE_ID_LEN    2
#define MIC3_UP_PGA_THRE_ID_OFFSET 7
#define MIC3_UP_PGA_ZERO_NUM_LEN    5
#define MIC3_UP_PGA_ZERO_NUM_OFFSET 2
#define MIC3_UP_PGA_LINEAR_SEL_LEN    1
#define MIC3_UP_PGA_LINEAR_SEL_OFFSET 1

#define SRCUP_CTRL_REG                     (ASP_CODEC_BASE + 0x58)            /* SRCUP控制寄存器 */
#define VOICE_L_DN_SRCUP_FIFO_CLR_LEN    1
#define VOICE_L_DN_SRCUP_FIFO_CLR_OFFSET 31
#define VOICE_L_DN_SRCUP_SRC_MODE_LEN    3
#define VOICE_L_DN_SRCUP_SRC_MODE_OFFSET 28
#define DACL_SRCUP_FIFO_CLR_LEN    1
#define DACL_SRCUP_FIFO_CLR_OFFSET 27
#define DACL_SRCUP_SRC_MODE_LEN    3
#define DACL_SRCUP_SRC_MODE_OFFSET 24
#define DACR_SRCUP_FIFO_CLR_LEN    1
#define DACR_SRCUP_FIFO_CLR_OFFSET 23
#define DACR_SRCUP_SRC_MODE_LEN    3
#define DACR_SRCUP_SRC_MODE_OFFSET 20
#define AUDIO_L_UP_SRCUP_FIFO_CLR_LEN    1
#define AUDIO_L_UP_SRCUP_FIFO_CLR_OFFSET 19
#define AUDIO_L_UP_SRCUP_SRC_MODE_LEN    3
#define AUDIO_L_UP_SRCUP_SRC_MODE_OFFSET 16
#define AUDIO_R_UP_SRCUP_FIFO_CLR_LEN    1
#define AUDIO_R_UP_SRCUP_FIFO_CLR_OFFSET 15
#define AUDIO_R_UP_SRCUP_SRC_MODE_LEN    3
#define AUDIO_R_UP_SRCUP_SRC_MODE_OFFSET 12
#define BT_L_RX_SRCUP_FIFO_CLR_LEN    1
#define BT_L_RX_SRCUP_FIFO_CLR_OFFSET 11
#define BT_L_RX_SRCUP_SRC_MODE_LEN    3
#define BT_L_RX_SRCUP_SRC_MODE_OFFSET 8
#define BT_R_RX_SRCUP_FIFO_CLR_LEN    1
#define BT_R_RX_SRCUP_FIFO_CLR_OFFSET 7
#define BT_R_RX_SRCUP_SRC_MODE_LEN    3
#define BT_R_RX_SRCUP_SRC_MODE_OFFSET 4
#define VOICE_R_DN_SRCUP_FIFO_CLR_LEN    1
#define VOICE_R_DN_SRCUP_FIFO_CLR_OFFSET 3
#define VOICE_R_DN_SRCUP_SRC_MODE_LEN    3
#define VOICE_R_DN_SRCUP_SRC_MODE_OFFSET 0

#define SRCDN_CTRL_REG                     (ASP_CODEC_BASE + 0x5C)            /* SRCDN控制寄存器 */
#define VOICE_L_UP_SRCDN_FIFO_CLR_LEN    1
#define VOICE_L_UP_SRCDN_FIFO_CLR_OFFSET 31
#define VOICE_L_UP_SRCDN_SRC_MODE_LEN    3
#define VOICE_L_UP_SRCDN_SRC_MODE_OFFSET 28
#define VOICE_R_UP_SRCDN_FIFO_CLR_LEN    1
#define VOICE_R_UP_SRCDN_FIFO_CLR_OFFSET 27
#define VOICE_R_UP_SRCDN_SRC_MODE_LEN    3
#define VOICE_R_UP_SRCDN_SRC_MODE_OFFSET 24
#define MIC3_UP_SRCDN_FIFO_CLR_LEN    1
#define MIC3_UP_SRCDN_FIFO_CLR_OFFSET 23
#define MIC3_UP_SRCDN_SRC_MODE_LEN    3
#define MIC3_UP_SRCDN_SRC_MODE_OFFSET 20
#define BT_L_RX_SRCDN_FIFO_CLR_LEN    1
#define BT_L_RX_SRCDN_FIFO_CLR_OFFSET 19
#define BT_L_RX_SRCDN_SRC_MODE_LEN    3
#define BT_L_RX_SRCDN_SRC_MODE_OFFSET 16
#define BT_R_RX_SRCDN_FIFO_CLR_LEN    1
#define BT_R_RX_SRCDN_FIFO_CLR_OFFSET 15
#define BT_R_RX_SRCDN_SRC_MODE_LEN    3
#define BT_R_RX_SRCDN_SRC_MODE_OFFSET 12
#define BT_TX_SRCDN_FIFO_CLR_LEN    1
#define BT_TX_SRCDN_FIFO_CLR_OFFSET 11
#define BT_TX_SRCDN_SRC_MODE_LEN    3
#define BT_TX_SRCDN_SRC_MODE_OFFSET 8
#define ECHO_L_UP_SRCDN_FIFO_CLR_LEN    1
#define ECHO_L_UP_SRCDN_FIFO_CLR_OFFSET 7
#define ECHO_L_UP_SRCDN_SRC_MODE_LEN    3
#define ECHO_L_UP_SRCDN_SRC_MODE_OFFSET 4
#define ECHO_R_UP_SRCDN_FIFO_CLR_LEN    1
#define ECHO_R_UP_SRCDN_FIFO_CLR_OFFSET 3
#define ECHO_R_UP_SRCDN_SRC_MODE_LEN    3
#define ECHO_R_UP_SRCDN_SRC_MODE_OFFSET 0

#define DACL_MIXER4_CTRL0_REG              (ASP_CODEC_BASE + 0x60)            /* DACL_MIXER4控制寄存器0 */
#define DACL_MIXER4_IN4_ID_LEN    2
#define DACL_MIXER4_IN4_ID_OFFSET 30
#define DACL_MIXER4_IN3_ID_LEN    2
#define DACL_MIXER4_IN3_ID_OFFSET 28
#define DACL_MIXER4_IN2_ID_LEN    2
#define DACL_MIXER4_IN2_ID_OFFSET 26
#define DACL_MIXER4_IN1_ID_LEN    2
#define DACL_MIXER4_IN1_ID_OFFSET 24
#define DACL_MIXER4_IN4_MUTE_LEN    1
#define DACL_MIXER4_IN4_MUTE_OFFSET 23
#define DACL_MIXER4_IN3_MUTE_LEN    1
#define DACL_MIXER4_IN3_MUTE_OFFSET 22
#define DACL_MIXER4_IN2_MUTE_LEN    1
#define DACL_MIXER4_IN2_MUTE_OFFSET 21
#define DACL_MIXER4_IN1_MUTE_LEN    1
#define DACL_MIXER4_IN1_MUTE_OFFSET 20
#define DACL_MIXER4_GAIN4_LEN    2
#define DACL_MIXER4_GAIN4_OFFSET 18
#define DACL_MIXER4_GAIN3_LEN    2
#define DACL_MIXER4_GAIN3_OFFSET 16
#define DACL_MIXER4_GAIN2_LEN    2
#define DACL_MIXER4_GAIN2_OFFSET 14
#define DACL_MIXER4_GAIN1_LEN    2
#define DACL_MIXER4_GAIN1_OFFSET 12

#define DACL_MIXER4_CTRL1_REG              (ASP_CODEC_BASE + 0x64)            /* DACL_MIXER4控制寄存器1 */
#define DACL_MIXER4_FADE_EN_LEN    1
#define DACL_MIXER4_FADE_EN_OFFSET 31
#define DACL_MIXER4_FADE_IN_LEN    5
#define DACL_MIXER4_FADE_IN_OFFSET 26
#define DACL_MIXER4_FADE_OUT_LEN    5
#define DACL_MIXER4_FADE_OUT_OFFSET 21
#define DACL_MIXER4_ZERO_NUM_LEN    5
#define DACL_MIXER4_ZERO_NUM_OFFSET 16

#define DACR_MIXER4_CTRL0_REG              (ASP_CODEC_BASE + 0x68)            /* DACR_MIXER4控制寄存器0 */
#define DACR_MIXER4_IN4_ID_LEN    2
#define DACR_MIXER4_IN4_ID_OFFSET 30
#define DACR_MIXER4_IN3_ID_LEN    2
#define DACR_MIXER4_IN3_ID_OFFSET 28
#define DACR_MIXER4_IN2_ID_LEN    2
#define DACR_MIXER4_IN2_ID_OFFSET 26
#define DACR_MIXER4_IN1_ID_LEN    2
#define DACR_MIXER4_IN1_ID_OFFSET 24
#define DACR_MIXER4_IN4_MUTE_LEN    1
#define DACR_MIXER4_IN4_MUTE_OFFSET 23
#define DACR_MIXER4_IN3_MUTE_LEN    1
#define DACR_MIXER4_IN3_MUTE_OFFSET 22
#define DACR_MIXER4_IN2_MUTE_LEN    1
#define DACR_MIXER4_IN2_MUTE_OFFSET 21
#define DACR_MIXER4_IN1_MUTE_LEN    1
#define DACR_MIXER4_IN1_MUTE_OFFSET 20
#define DACR_MIXER4_GAIN4_LEN    2
#define DACR_MIXER4_GAIN4_OFFSET 18
#define DACR_MIXER4_GAIN3_LEN    2
#define DACR_MIXER4_GAIN3_OFFSET 16
#define DACR_MIXER4_GAIN2_LEN    2
#define DACR_MIXER4_GAIN2_OFFSET 14
#define DACR_MIXER4_GAIN1_LEN    2
#define DACR_MIXER4_GAIN1_OFFSET 12

#define DACR_MIXER4_CTRL1_REG              (ASP_CODEC_BASE + 0x6C)            /* DACR_MIXER4控制寄存器1 */
#define DACR_MIXER4_FADE_EN_LEN    1
#define DACR_MIXER4_FADE_EN_OFFSET 31
#define DACR_MIXER4_FADE_IN_LEN    5
#define DACR_MIXER4_FADE_IN_OFFSET 26
#define DACR_MIXER4_FADE_OUT_LEN    5
#define DACR_MIXER4_FADE_OUT_OFFSET 21
#define DACR_MIXER4_ZERO_NUM_LEN    5
#define DACR_MIXER4_ZERO_NUM_OFFSET 16

#define BT_TX_MIXER2_CTRL_REG              (ASP_CODEC_BASE + 0x70)            /* BT_TX_MIXER2控制寄存器 */
#define BT_TX_MIXER2_IN2_ID_LEN    2
#define BT_TX_MIXER2_IN2_ID_OFFSET 30
#define BT_TX_MIXER2_IN1_ID_LEN    2
#define BT_TX_MIXER2_IN1_ID_OFFSET 28
#define BT_TX_MIXER2_IN2_MUTE_LEN    1
#define BT_TX_MIXER2_IN2_MUTE_OFFSET 27
#define BT_TX_MIXER2_IN1_MUTE_LEN    1
#define BT_TX_MIXER2_IN1_MUTE_OFFSET 26
#define BT_TX_MIXER2_GAIN2_LEN    2
#define BT_TX_MIXER2_GAIN2_OFFSET 24
#define BT_TX_MIXER2_GAIN1_LEN    2
#define BT_TX_MIXER2_GAIN1_OFFSET 22
#define BT_TX_MIXER2_FADE_EN_LEN    1
#define BT_TX_MIXER2_FADE_EN_OFFSET 21
#define BT_TX_MIXER2_FADE_IN_LEN    5
#define BT_TX_MIXER2_FADE_IN_OFFSET 16
#define BT_TX_MIXER2_FADE_OUT_LEN    5
#define BT_TX_MIXER2_FADE_OUT_OFFSET 11
#define BT_TX_MIXER2_ZERO_NUM_LEN    5
#define BT_TX_MIXER2_ZERO_NUM_OFFSET 6

#define DAC_FILTER_CTRL_REG                (ASP_CODEC_BASE + 0x74)            /* DAC_FILTER控制寄存器 */
#define DACL_FIR2C_BYPASS_EN_LEN    1
#define DACL_FIR2C_BYPASS_EN_OFFSET 31
#define DACL_FIR2D_BYPASS_EN_LEN    1
#define DACL_FIR2D_BYPASS_EN_OFFSET 30
#define DACR_FIR2C_BYPASS_EN_LEN    1
#define DACR_FIR2C_BYPASS_EN_OFFSET 29
#define DACR_FIR2D_BYPASS_EN_LEN    1
#define DACR_FIR2D_BYPASS_EN_OFFSET 28
#define SDM_L_DITHER_LEN    1
#define SDM_L_DITHER_OFFSET 19
#define SDM_L_CALT_VLD_LEN    1
#define SDM_L_CALT_VLD_OFFSET 18
#define SDM_R_DITHER_LEN    1
#define SDM_R_DITHER_OFFSET 17
#define SDM_R_CALT_VLD_LEN    1
#define SDM_R_CALT_VLD_OFFSET 16
#define SIF_MST_S2P_LOOPBACK_LEN    2
#define SIF_MST_S2P_LOOPBACK_OFFSET 14
#define SIF_MST_P2S_LOOPBACK_LEN    2
#define SIF_MST_P2S_LOOPBACK_OFFSET 12
#define SIF_MST_DACR_EN_LEN    1
#define SIF_MST_DACR_EN_OFFSET 11
#define SIF_MST_DACL_EN_LEN    1
#define SIF_MST_DACL_EN_OFFSET 10
#define SIF_MST_ADCR_EN_LEN    1
#define SIF_MST_ADCR_EN_OFFSET 9
#define SIF_MST_ADCL_EN_LEN    1
#define SIF_MST_ADCL_EN_OFFSET 8
#define SIF_MST_ADC_MIC3_EN_LEN    1
#define SIF_MST_ADC_MIC3_EN_OFFSET 7
#define SIF_MST_DAC_EDGE_SEL_LEN    1
#define SIF_MST_DAC_EDGE_SEL_OFFSET 6
#define SIF_MST_ADC_EDGE_SEL_LEN    1
#define SIF_MST_ADC_EDGE_SEL_OFFSET 5

#define ADC_FILTER_CTRL_REG                (ASP_CODEC_BASE + 0x78)            /* ADC_FILTER控制寄存器 */
#define ADCL_CIC_GAIN_LEN    6
#define ADCL_CIC_GAIN_OFFSET 26
#define ADCL_COMPD_BYPASS_EN_LEN    1
#define ADCL_COMPD_BYPASS_EN_OFFSET 25
#define ADCL_HBF2D_BYPASS_EN_LEN    1
#define ADCL_HBF2D_BYPASS_EN_OFFSET 24
#define ADCL_HBFVD_BYPASS_EN_LEN    1
#define ADCL_HBFVD_BYPASS_EN_OFFSET 23
#define ADCL_HPF_BYPASS_EN_LEN    1
#define ADCL_HPF_BYPASS_EN_OFFSET 22
#define ADCR_CIC_GAIN_LEN    6
#define ADCR_CIC_GAIN_OFFSET 16
#define ADCR_COMPD_BYPASS_EN_LEN    1
#define ADCR_COMPD_BYPASS_EN_OFFSET 15
#define ADCR_HBF2D_BYPASS_EN_LEN    1
#define ADCR_HBF2D_BYPASS_EN_OFFSET 14
#define ADCR_HBFVD_BYPASS_EN_LEN    1
#define ADCR_HBFVD_BYPASS_EN_OFFSET 13
#define ADCR_HPF_BYPASS_EN_LEN    1
#define ADCR_HPF_BYPASS_EN_OFFSET 12
#define ADC_MIC3_CIC_GAIN_LEN    6
#define ADC_MIC3_CIC_GAIN_OFFSET 6
#define ADC_MIC3_COMPD_BYPASS_EN_LEN    1
#define ADC_MIC3_COMPD_BYPASS_EN_OFFSET 5
#define ADC_MIC3_HBF2D_BYPASS_EN_LEN    1
#define ADC_MIC3_HBF2D_BYPASS_EN_OFFSET 4
#define ADC_MIC3_HBFVD_BYPASS_EN_LEN    1
#define ADC_MIC3_HBFVD_BYPASS_EN_OFFSET 3
#define ADC_MIC3_HPF_BYPASS_EN_LEN    1
#define ADC_MIC3_HPF_BYPASS_EN_OFFSET 2

#define SPA_UP_AFIFO_CTRL_REG              (ASP_CODEC_BASE + 0x7C)            /* SPA反馈通路AFIFO控制寄存器 */
#define SPA_L_UP_FIFO_CLR_LEN    1
#define SPA_L_UP_FIFO_CLR_OFFSET 31
#define SPA_L_UP_FIFO_AFULL_TH_LEN    5
#define SPA_L_UP_FIFO_AFULL_TH_OFFSET 26
#define SPA_L_UP_FIFO_AEMPTY_TH_LEN    5
#define SPA_L_UP_FIFO_AEMPTY_TH_OFFSET 21
#define SPA_R_UP_FIFO_CLR_LEN    1
#define SPA_R_UP_FIFO_CLR_OFFSET 15
#define SPA_R_UP_FIFO_AFULL_TH_LEN    5
#define SPA_R_UP_FIFO_AFULL_TH_OFFSET 10
#define SPA_R_UP_FIFO_AEMPTY_TH_LEN    5
#define SPA_R_UP_FIFO_AEMPTY_TH_OFFSET 5

#define AUDIO_DN_AFIFO_CTRL_REG            (ASP_CODEC_BASE + 0x80)            /* AUDIO下行通路AFIFO控制寄存器 */
#define AUDIO_L_DN_FIFO_CLR_LEN    1
#define AUDIO_L_DN_FIFO_CLR_OFFSET 31
#define AUDIO_L_DN_FIFO_AFULL_TH_LEN    5
#define AUDIO_L_DN_FIFO_AFULL_TH_OFFSET 26
#define AUDIO_L_DN_FIFO_AEMPTY_TH_LEN    5
#define AUDIO_L_DN_FIFO_AEMPTY_TH_OFFSET 21
#define AUDIO_R_DN_FIFO_CLR_LEN    1
#define AUDIO_R_DN_FIFO_CLR_OFFSET 15
#define AUDIO_R_DN_FIFO_AFULL_TH_LEN    5
#define AUDIO_R_DN_FIFO_AFULL_TH_OFFSET 10
#define AUDIO_R_DN_FIFO_AEMPTY_TH_LEN    5
#define AUDIO_R_DN_FIFO_AEMPTY_TH_OFFSET 5

#define AUDIO_UP_AFIFO_CTRL_REG            (ASP_CODEC_BASE + 0x84)            /* AUDIO上行通路AFIFO控制寄存器 */
#define AUDIO_L_UP_FIFO_CLR_LEN    1
#define AUDIO_L_UP_FIFO_CLR_OFFSET 31
#define AUDIO_L_UP_FIFO_AFULL_TH_LEN    5
#define AUDIO_L_UP_FIFO_AFULL_TH_OFFSET 26
#define AUDIO_L_UP_FIFO_AEMPTY_TH_LEN    5
#define AUDIO_L_UP_FIFO_AEMPTY_TH_OFFSET 21
#define AUDIO_R_UP_FIFO_CLR_LEN    1
#define AUDIO_R_UP_FIFO_CLR_OFFSET 15
#define AUDIO_R_UP_FIFO_AFULL_TH_LEN    5
#define AUDIO_R_UP_FIFO_AFULL_TH_OFFSET 10
#define AUDIO_R_UP_FIFO_AEMPTY_TH_LEN    5
#define AUDIO_R_UP_FIFO_AEMPTY_TH_OFFSET 5

#define VOICE_UP_AFIFO_CTRL_REG            (ASP_CODEC_BASE + 0x88)            /* VOICE上行通路AFIFO控制寄存器 */
#define VOICE_L_UP_FIFO_CLR_LEN    1
#define VOICE_L_UP_FIFO_CLR_OFFSET 31
#define VOICE_L_UP_FIFO_AFULL_TH_LEN    5
#define VOICE_L_UP_FIFO_AFULL_TH_OFFSET 26
#define VOICE_L_UP_FIFO_AEMPTY_TH_LEN    5
#define VOICE_L_UP_FIFO_AEMPTY_TH_OFFSET 21
#define VOICE_R_UP_FIFO_CLR_LEN    1
#define VOICE_R_UP_FIFO_CLR_OFFSET 15
#define VOICE_R_UP_FIFO_AFULL_TH_LEN    5
#define VOICE_R_UP_FIFO_AFULL_TH_OFFSET 10
#define VOICE_R_UP_FIFO_AEMPTY_TH_LEN    5
#define VOICE_R_UP_FIFO_AEMPTY_TH_OFFSET 5

#define ECHO_UP_AFIFO_CTRL_REG             (ASP_CODEC_BASE + 0x8C)            /* ECHO上行通路AFIFO控制寄存器 */
#define ECHO_L_UP_FIFO_CLR_LEN    1
#define ECHO_L_UP_FIFO_CLR_OFFSET 31
#define ECHO_L_UP_FIFO_AFULL_TH_LEN    5
#define ECHO_L_UP_FIFO_AFULL_TH_OFFSET 26
#define ECHO_L_UP_FIFO_AEMPTY_TH_LEN    5
#define ECHO_L_UP_FIFO_AEMPTY_TH_OFFSET 21
#define ECHO_R_UP_FIFO_CLR_LEN    1
#define ECHO_R_UP_FIFO_CLR_OFFSET 15
#define ECHO_R_UP_FIFO_AFULL_TH_LEN    5
#define ECHO_R_UP_FIFO_AFULL_TH_OFFSET 10
#define ECHO_R_UP_FIFO_AEMPTY_TH_LEN    5
#define ECHO_R_UP_FIFO_AEMPTY_TH_OFFSET 5

#define VOICE_DN_AFIFO_CTRL_REG            (ASP_CODEC_BASE + 0x90)            /* VOICE下行通路AFIFO控制寄存器 */
#define VOICE_L_DN_FIFO_CLR_LEN    1
#define VOICE_L_DN_FIFO_CLR_OFFSET 31
#define VOICE_L_DN_FIFO_AFULL_TH_LEN    5
#define VOICE_L_DN_FIFO_AFULL_TH_OFFSET 26
#define VOICE_L_DN_FIFO_AEMPTY_TH_LEN    5
#define VOICE_L_DN_FIFO_AEMPTY_TH_OFFSET 21
#define VOICE_R_DN_FIFO_CLR_LEN    1
#define VOICE_R_DN_FIFO_CLR_OFFSET 15
#define VOICE_R_DN_FIFO_AFULL_TH_LEN    5
#define VOICE_R_DN_FIFO_AFULL_TH_OFFSET 10
#define VOICE_R_DN_FIFO_AEMPTY_TH_LEN    5
#define VOICE_R_DN_FIFO_AEMPTY_TH_OFFSET 5

#define MIC3_UP_AFIFO_CTRL_REG             (ASP_CODEC_BASE + 0x94)            /* MIC3上行通路AFIFO控制寄存器 */
#define MIC3_UP_FIFO_CLR_LEN    1
#define MIC3_UP_FIFO_CLR_OFFSET 31
#define MIC3_UP_FIFO_AFULL_TH_LEN    5
#define MIC3_UP_FIFO_AFULL_TH_OFFSET 26
#define MIC3_UP_FIFO_AEMPTY_TH_LEN    5
#define MIC3_UP_FIFO_AEMPTY_TH_OFFSET 21

#define MEM_CTRL_CFG_REG                   (ASP_CODEC_BASE + 0x98)            /* MEMORY CTRL配置信号 */
#define MEM_CTRL_D1W2R_LEN    16
#define MEM_CTRL_D1W2R_OFFSET 16
#define MEM_CTRL_S_LEN    16
#define MEM_CTRL_S_OFFSET 0

#define CODEC_STAT0_REG                    (ASP_CODEC_BASE + 0x9C)            /* CODEC通道内模块状态查询寄存器0 */
#define VOICE_L_DN_SRCUP_RDY_LEN    1
#define VOICE_L_DN_SRCUP_RDY_OFFSET 31
#define DACL_SRCUP_RDY_LEN    1
#define DACL_SRCUP_RDY_OFFSET 30
#define DACR_SRCUP_RDY_LEN    1
#define DACR_SRCUP_RDY_OFFSET 29
#define AUDIO_L_UP_SRCUP_RDY_LEN    1
#define AUDIO_L_UP_SRCUP_RDY_OFFSET 28
#define AUDIO_R_UP_SRCUP_RDY_LEN    1
#define AUDIO_R_UP_SRCUP_RDY_OFFSET 27
#define VOICE_L_UP_SRCDN_RDY_LEN    1
#define VOICE_L_UP_SRCDN_RDY_OFFSET 26
#define VOICE_R_UP_SRCDN_RDY_LEN    1
#define VOICE_R_UP_SRCDN_RDY_OFFSET 25
#define MIC3_UP_SRCDN_RDY_LEN    1
#define MIC3_UP_SRCDN_RDY_OFFSET 24
#define BT_L_RX_SRCUP_RDY_LEN    1
#define BT_L_RX_SRCUP_RDY_OFFSET 23
#define BT_R_RX_SRCUP_RDY_LEN    1
#define BT_R_RX_SRCUP_RDY_OFFSET 22
#define BT_L_RX_SRCDN_RDY_LEN    1
#define BT_L_RX_SRCDN_RDY_OFFSET 21
#define BT_R_RX_SRCDN_RDY_LEN    1
#define BT_R_RX_SRCDN_RDY_OFFSET 20
#define BT_TX_SRCDN_RDY_LEN    1
#define BT_TX_SRCDN_RDY_OFFSET 19
#define ECHO_L_UP_SRCDN_RDY_LEN    1
#define ECHO_L_UP_SRCDN_RDY_OFFSET 18
#define ECHO_R_UP_SRCDN_RDY_LEN    1
#define ECHO_R_UP_SRCDN_RDY_OFFSET 17
#define VOICE_R_DN_SRCUP_RDY_LEN    1
#define VOICE_R_DN_SRCUP_RDY_OFFSET 16
#define TDM1_ERR_STAT_LEN    4
#define TDM1_ERR_STAT_OFFSET 0

#define CODEC_STAT1_REG                    (ASP_CODEC_BASE + 0xA0)            /* CODEC通道内模块状态查询寄存器1 */
#define AUDIO_L_DN_AFIFO_WERROR_LEN    1
#define AUDIO_L_DN_AFIFO_WERROR_OFFSET 31
#define AUDIO_L_DN_AFIFO_RERROR_LEN    1
#define AUDIO_L_DN_AFIFO_RERROR_OFFSET 30
#define AUDIO_L_UP_AFIFO_WERROR_LEN    1
#define AUDIO_L_UP_AFIFO_WERROR_OFFSET 29
#define AUDIO_L_UP_AFIFO_RERROR_LEN    1
#define AUDIO_L_UP_AFIFO_RERROR_OFFSET 28
#define AUDIO_R_DN_AFIFO_WERROR_LEN    1
#define AUDIO_R_DN_AFIFO_WERROR_OFFSET 27
#define AUDIO_R_DN_AFIFO_RERROR_LEN    1
#define AUDIO_R_DN_AFIFO_RERROR_OFFSET 26
#define AUDIO_R_UP_AFIFO_WERROR_LEN    1
#define AUDIO_R_UP_AFIFO_WERROR_OFFSET 25
#define AUDIO_R_UP_AFIFO_RERROR_LEN    1
#define AUDIO_R_UP_AFIFO_RERROR_OFFSET 24
#define ECHO_L_UP_AFIFO_WERROR_LEN    1
#define ECHO_L_UP_AFIFO_WERROR_OFFSET 23
#define ECHO_L_UP_AFIFO_RERROR_LEN    1
#define ECHO_L_UP_AFIFO_RERROR_OFFSET 22
#define ECHO_R_UP_AFIFO_WERROR_LEN    1
#define ECHO_R_UP_AFIFO_WERROR_OFFSET 21
#define ECHO_R_UP_AFIFO_RERROR_LEN    1
#define ECHO_R_UP_AFIFO_RERROR_OFFSET 20
#define MIC3_UP_AFIFO_WERROR_LEN    1
#define MIC3_UP_AFIFO_WERROR_OFFSET 19
#define MIC3_UP_AFIFO_RERROR_LEN    1
#define MIC3_UP_AFIFO_RERROR_OFFSET 18
#define SPA_L_UP_AFIFO_WERROR_LEN    1
#define SPA_L_UP_AFIFO_WERROR_OFFSET 17
#define SPA_L_UP_AFIFO_RERROR_LEN    1
#define SPA_L_UP_AFIFO_RERROR_OFFSET 16
#define SPA_R_UP_AFIFO_WERROR_LEN    1
#define SPA_R_UP_AFIFO_WERROR_OFFSET 15
#define SPA_R_UP_AFIFO_RERROR_LEN    1
#define SPA_R_UP_AFIFO_RERROR_OFFSET 14
#define VOICE_L_DN_AFIFO_WERROR_LEN    1
#define VOICE_L_DN_AFIFO_WERROR_OFFSET 13
#define VOICE_L_DN_AFIFO_RERROR_LEN    1
#define VOICE_L_DN_AFIFO_RERROR_OFFSET 12
#define VOICE_L_UP_AFIFO_WERROR_LEN    1
#define VOICE_L_UP_AFIFO_WERROR_OFFSET 11
#define VOICE_L_UP_AFIFO_RERROR_LEN    1
#define VOICE_L_UP_AFIFO_RERROR_OFFSET 10
#define VOICE_R_UP_AFIFO_WERROR_LEN    1
#define VOICE_R_UP_AFIFO_WERROR_OFFSET 9
#define VOICE_R_UP_AFIFO_RERROR_LEN    1
#define VOICE_R_UP_AFIFO_RERROR_OFFSET 8
#define VOICE_R_DN_AFIFO_WERROR_LEN    1
#define VOICE_R_DN_AFIFO_WERROR_OFFSET 7
#define VOICE_R_DN_AFIFO_RERROR_LEN    1
#define VOICE_R_DN_AFIFO_RERROR_OFFSET 6
#define CODEC3_L_DN_AFIFO_WERROR_LEN    1
#define CODEC3_L_DN_AFIFO_WERROR_OFFSET 5
#define CODEC3_L_DN_AFIFO_RERROR_LEN    1
#define CODEC3_L_DN_AFIFO_RERROR_OFFSET 4
#define CODEC3_R_DN_AFIFO_WERROR_LEN    1
#define CODEC3_R_DN_AFIFO_WERROR_OFFSET 3
#define CODEC3_R_DN_AFIFO_RERROR_LEN    1
#define CODEC3_R_DN_AFIFO_RERROR_OFFSET 2

#define FS_CTRL0_REG                       (ASP_CODEC_BASE + 0xA4)            /* CODEC内部模块采样率控制寄存器0 */
#define FS_VOICE_L_DLINK_LEN    2
#define FS_VOICE_L_DLINK_OFFSET 30
#define FS_AUDIO_L_UPLINK_LEN    1
#define FS_AUDIO_L_UPLINK_OFFSET 29
#define FS_AUDIO_R_UPLINK_LEN    1
#define FS_AUDIO_R_UPLINK_OFFSET 28
#define FS_VOICE_L_UPLINK_LEN    2
#define FS_VOICE_L_UPLINK_OFFSET 26
#define FS_VOICE_R_UPLINK_LEN    2
#define FS_VOICE_R_UPLINK_OFFSET 24
#define FS_MIC3_UPLINK_LEN    3
#define FS_MIC3_UPLINK_OFFSET 21
#define FS_ECHO_L_UPLINK_LEN    3
#define FS_ECHO_L_UPLINK_OFFSET 18
#define FS_ECHO_R_UPLINK_LEN    3
#define FS_ECHO_R_UPLINK_OFFSET 15
#define FS_VOICE_L_DN_SRCUP_IN_LEN    2
#define FS_VOICE_L_DN_SRCUP_IN_OFFSET 13
#define FS_DACL_SRCUP_IN_LEN    2
#define FS_DACL_SRCUP_IN_OFFSET 11
#define FS_DACR_SRCUP_IN_LEN    2
#define FS_DACR_SRCUP_IN_OFFSET 9
#define FS_AUDIO_L_UP_SRCUP_IN_LEN    2
#define FS_AUDIO_L_UP_SRCUP_IN_OFFSET 7
#define FS_AUDIO_R_UP_SRCUP_IN_LEN    2
#define FS_AUDIO_R_UP_SRCUP_IN_OFFSET 5

#define FS_CTRL1_REG                       (ASP_CODEC_BASE + 0xA8)            /* CODEC内部模块采样率控制寄存器1 */
#define FS_BT_L_RX_SRCUP_IN_LEN    2
#define FS_BT_L_RX_SRCUP_IN_OFFSET 30
#define FS_BT_L_RX_SRCUP_OUT_LEN    2
#define FS_BT_L_RX_SRCUP_OUT_OFFSET 28
#define FS_BT_R_RX_SRCUP_IN_LEN    2
#define FS_BT_R_RX_SRCUP_IN_OFFSET 26
#define FS_BT_R_RX_SRCUP_OUT_LEN    2
#define FS_BT_R_RX_SRCUP_OUT_OFFSET 24
#define FS_VOICE_L_UP_SRCDN_OUT_LEN    2
#define FS_VOICE_L_UP_SRCDN_OUT_OFFSET 22
#define FS_VOICE_R_UP_SRCDN_OUT_LEN    2
#define FS_VOICE_R_UP_SRCDN_OUT_OFFSET 20
#define FS_MIC3_UP_SRCDN_OUT_LEN    2
#define FS_MIC3_UP_SRCDN_OUT_OFFSET 18
#define FS_ECHO_L_UP_SRCDN_OUT_LEN    2
#define FS_ECHO_L_UP_SRCDN_OUT_OFFSET 16
#define FS_ECHO_R_UP_SRCDN_OUT_LEN    2
#define FS_ECHO_R_UP_SRCDN_OUT_OFFSET 14
#define FS_BT_L_RX_SRCDN_IN_LEN    2
#define FS_BT_L_RX_SRCDN_IN_OFFSET 12
#define FS_BT_L_RX_SRCDN_OUT_LEN    2
#define FS_BT_L_RX_SRCDN_OUT_OFFSET 10
#define FS_BT_R_RX_SRCDN_IN_LEN    2
#define FS_BT_R_RX_SRCDN_IN_OFFSET 8
#define FS_BT_R_RX_SRCDN_OUT_LEN    2
#define FS_BT_R_RX_SRCDN_OUT_OFFSET 6
#define FS_BT_TX_SRCDN_OUT_LEN    2
#define FS_BT_TX_SRCDN_OUT_OFFSET 4

#define CODEC_DIN_MUX_REG                  (ASP_CODEC_BASE + 0xAC)            /* CODEC内部模块输入数据选择寄存器 */
#define BM_26TO32_PA_L_DIN_SEL_LEN    1
#define BM_26TO32_PA_L_DIN_SEL_OFFSET 31
#define BM_26TO32_PA_R_DIN_SEL_LEN    1
#define BM_26TO32_PA_R_DIN_SEL_OFFSET 30
#define DACL_SRCUP_DIN_SEL_LEN    2
#define DACL_SRCUP_DIN_SEL_OFFSET 28
#define DACR_SRCUP_DIN_SEL_LEN    2
#define DACR_SRCUP_DIN_SEL_OFFSET 26
#define SIDETONE_PGA_DIN_SEL_LEN    2
#define SIDETONE_PGA_DIN_SEL_OFFSET 24
#define BM_26TO24_AUDIO_L_UP_DIN_SEL_LEN    2
#define BM_26TO24_AUDIO_L_UP_DIN_SEL_OFFSET 22
#define BM_26TO24_AUDIO_R_UP_DIN_SEL_LEN    2
#define BM_26TO24_AUDIO_R_UP_DIN_SEL_OFFSET 20
#define AUDIO_L_UP_AFIFO_DIN_SEL_LEN    1
#define AUDIO_L_UP_AFIFO_DIN_SEL_OFFSET 19
#define AUDIO_R_UP_AFIFO_DIN_SEL_LEN    1
#define AUDIO_R_UP_AFIFO_DIN_SEL_OFFSET 18
#define BM_26TO24_VOICE_L_UP_DIN_SEL_LEN    1
#define BM_26TO24_VOICE_L_UP_DIN_SEL_OFFSET 17
#define BM_26TO24_VOICE_R_UP_DIN_SEL_LEN    1
#define BM_26TO24_VOICE_R_UP_DIN_SEL_OFFSET 16
#define MIC3_UP_AFIFO_DIN_SEL_LEN    1
#define MIC3_UP_AFIFO_DIN_SEL_OFFSET 15
#define ADCL_DIN_SEL_LEN    2
#define ADCL_DIN_SEL_OFFSET 13
#define ADCR_DIN_SEL_LEN    2
#define ADCR_DIN_SEL_OFFSET 11
#define ADC_MIC3_DIN_SEL_LEN    2
#define ADC_MIC3_DIN_SEL_OFFSET 9
#define BM_26TO24_ECHO_L_UP_DIN_SEL_LEN    1
#define BM_26TO24_ECHO_L_UP_DIN_SEL_OFFSET 8
#define BM_26TO24_ECHO_R_UP_DIN_SEL_LEN    1
#define BM_26TO24_ECHO_R_UP_DIN_SEL_OFFSET 7

#define CODEC_INT_STAT_REG                 (ASP_CODEC_BASE + 0xB0)            /* CODEC内部中断状态查询 */
#define PINT_LEN    15
#define PINT_OFFSET 17

#define CODEC_DACL_DC_OFFSET_REG           (ASP_CODEC_BASE + 0xB4)            /* DACL通路DC_OFFSET配置寄存器 */
#define DACL_DC_OFFSET_LEN    24
#define DACL_DC_OFFSET_OFFSET 0

#define CODEC_DACR_DC_OFFSET_REG           (ASP_CODEC_BASE + 0xB8)            /* DACR通路DC_OFFSET配置寄存器 */
#define DACR_DC_OFFSET_LEN    24
#define DACR_DC_OFFSET_OFFSET 0

#define CODEC_ADCL_DC_OFFSET_REG           (ASP_CODEC_BASE + 0xBC)            /* ADCL通路DC_OFFSET配置寄存器 */
#define ADCL_DC_OFFSET_LEN    24
#define ADCL_DC_OFFSET_OFFSET 0

#define CODEC_ADCR_DC_OFFSET_REG           (ASP_CODEC_BASE + 0xC0)            /* ADCR通路DC_OFFSET配置寄存器 */
#define ADCR_DC_OFFSET_LEN    24
#define ADCR_DC_OFFSET_OFFSET 0

#define CODEC_ADC_MIC3_DC_OFFSET_REG       (ASP_CODEC_BASE + 0xC4)            /* ADC_MIC3通路DC_OFFSET配置寄存器 */
#define ADC_MIC3_DC_OFFSET_LEN    24
#define ADC_MIC3_DC_OFFSET_OFFSET 0

#define I2S3_PCM_CTRL_REG                  (ASP_CODEC_BASE + 0xC8)
#define I2S3_RX_CLK_SEL_LEN    1
#define I2S3_RX_CLK_SEL_OFFSET 19
#define I2S3_TX_CLK_SEL_LEN    1
#define I2S3_TX_CLK_SEL_OFFSET 18
#define I2S3_CODEC_IO_WORDLENGTH_LEN    2
#define I2S3_CODEC_IO_WORDLENGTH_OFFSET 16
#define I2S3_CODEC_DATA_FORMAT_LEN    1
#define I2S3_CODEC_DATA_FORMAT_OFFSET 14
#define I2S3_CHNNL_MODE_LEN    1
#define I2S3_CHNNL_MODE_OFFSET 13
#define I2S3_LRCLK_MODE_LEN    1
#define I2S3_LRCLK_MODE_OFFSET 12
#define I2S3_FRAME_MODE_LEN    1
#define I2S3_FRAME_MODE_OFFSET 11
#define I2S3_FUNC_MODE_LEN    3
#define I2S3_FUNC_MODE_OFFSET 8
#define I2S3_DIRECT_LOOP_LEN    2
#define I2S3_DIRECT_LOOP_OFFSET 6
#define I2S3_MST_SLV_LEN    1
#define I2S3_MST_SLV_OFFSET 5
#define I2S3_IF_RX_ENA_LEN    1
#define I2S3_IF_RX_ENA_OFFSET 4
#define I2S3_IF_TX_ENA_LEN    1
#define I2S3_IF_TX_ENA_OFFSET 3
#define FS_I2S3_LEN    3
#define FS_I2S3_OFFSET 0

#define VOICE_R_DN_PGA_CTRL_REG            (ASP_CODEC_BASE + 0xCC)
#define VOICE_R_DN_PGA_GAIN_LEN    8
#define VOICE_R_DN_PGA_GAIN_OFFSET 24
#define VOICE_R_DN_PGA_CFG_LEN    3
#define VOICE_R_DN_PGA_CFG_OFFSET 21
#define VOICE_R_DN_PGA_FADE_IN_LEN    5
#define VOICE_R_DN_PGA_FADE_IN_OFFSET 16
#define VOICE_R_DN_PGA_FADE_OUT_LEN    5
#define VOICE_R_DN_PGA_FADE_OUT_OFFSET 11
#define VOICE_R_DN_PGA_BYPASS_LEN    1
#define VOICE_R_DN_PGA_BYPASS_OFFSET 10
#define VOICE_R_DN_PGA_NOISE_EN_LEN    1
#define VOICE_R_DN_PGA_NOISE_EN_OFFSET 9
#define VOICE_R_DN_PGA_THRE_ID_LEN    2
#define VOICE_R_DN_PGA_THRE_ID_OFFSET 7
#define VOICE_R_DN_PGA_ZERO_NUM_LEN    5
#define VOICE_R_DN_PGA_ZERO_NUM_OFFSET 2
#define VOICE_R_DN_PGA_LINEAR_SEL_LEN    1
#define VOICE_R_DN_PGA_LINEAR_SEL_OFFSET 1

#define CODEC3_DN_AFIFO_CTRL_REG           (ASP_CODEC_BASE + 0xD0)
#define CODEC3_L_DN_FIFO_CLR_LEN    1
#define CODEC3_L_DN_FIFO_CLR_OFFSET 31
#define CODEC3_L_DN_FIFO_AFULL_TH_LEN    5
#define CODEC3_L_DN_FIFO_AFULL_TH_OFFSET 26
#define CODEC3_L_DN_FIFO_AEMPTY_TH_LEN    5
#define CODEC3_L_DN_FIFO_AEMPTY_TH_OFFSET 21
#define CODEC3_R_DN_FIFO_CLR_LEN    1
#define CODEC3_R_DN_FIFO_CLR_OFFSET 15
#define CODEC3_R_DN_FIFO_AFULL_TH_LEN    5
#define CODEC3_R_DN_FIFO_AFULL_TH_OFFSET 10
#define CODEC3_R_DN_FIFO_AEMPTY_TH_LEN    5
#define CODEC3_R_DN_FIFO_AEMPTY_TH_OFFSET 5

#define FS_CTRL2_REG                       (ASP_CODEC_BASE + 0xD4)
#define FS_CODEC3_L_DLINK_LEN    3
#define FS_CODEC3_L_DLINK_OFFSET 8
#define FS_CODEC3_R_DLINK_LEN    3
#define FS_CODEC3_R_DLINK_OFFSET 4
#define FS_VOICE_R_DN_SRCUP_IN_LEN    2
#define FS_VOICE_R_DN_SRCUP_IN_OFFSET 2
#define FS_VOICE_R_DLINK_LEN    2
#define FS_VOICE_R_DLINK_OFFSET 0

#define R_RST_CTRLEN						(ASP_CFG_BASE + 0x0)
#define RST_EN_CODEC_N 0

#define R_RST_CTRLDIS						(ASP_CFG_BASE + 0x4)
#define RST_DISEN_CODEC_N 0

#define R_GATE_EN							(ASP_CFG_BASE + 0xC)
#define GT_CODEC_CLK 1

#define R_CODEC_DMA_SEL					(ASP_CFG_BASE + 0x1D8)
#define CODEC_DMA_SEL 0

#endif /* __HI6555V2_ASP_REG_DEF_H__ */

